# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  app.mailer.transport: sendmail
    #parameter_name: value

services:
  app.mailer:
    class: AppBundle\Mailer
    arguements: ['%app.mailer.transport%']
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
